make the version check more verbose

diff --git a/utils/mp-server/new_release b/utils/mp-server/new_release
--- a/utils/mp-server/new_release
+++ b/utils/mp-server/new_release
@@ -30,7 +30,10 @@ $echo sed -i -e "/motd=/s/$PREV_VERSION/$NEW_VERSION/g" $PREV_SERVER_CONFIG
 # reload the config
 $echo killall -SIGHUP wesnothd-$DEV_VERSION-prev || exit 1
 # check if we currently allow the previous version to prevent announcing the same version twice
-$echo [ grep "versions_accepted=.*$PREV_VERSION" $DEV_SERVER_CONFIG ] || exit 1
+if [ $(grep "versions_accepted=.*$PREV_VERSION" $DEV_SERVER_CONFIG) ]; then
+	echo "Previous version $PREV_VERSION currently not allowed. Announcing the right version? Aborting..."
+	exit 1
+fi
 $echo sed -i -e "/versions_accepted=/s/$PREV_VERSION/$NEXT_VERSION/" $DEV_SERVER_CONFIG
 $echo sed -i -e "/motd=/s/$PREV_VERSION/$NEW_VERSION/g" $DEV_SERVER_CONFIG
 # update previous version redirect
