move the profile to a better place and exit on fatal errors

diff --git a/utils/mp-server/run_campaignd b/utils/mp-server/run_campaignd
--- a/utils/mp-server/run_campaignd
+++ b/utils/mp-server/run_campaignd
@@ -33,5 +33,9 @@ do
 	COMMAND="$HOME/bin/campaignd-$VERSION $THREADS $PARAMETERS"
 	echo "started $VERSION campaignd with command: '$COMMAND' at: $DATE"
 	$COMMAND &> $SERVERBASE/logs/campaignd.$DATE
-
+	mv gmon.out ../gmon.$DATE.out &> /dev/null
+	[ "$?" != "0" ] || exit
+	[ "$?" != "1" ] || die "File I/O error."
+	[ "$?" != "2" ] || die "Could not parse config file."
+	[ "$?" != "3" ] || die "Could not bind to port."
 done
