* give an error message when a non-existing server is used

diff --git a/utils/mp-server/send_server_command b/utils/mp-server/send_server_command
--- a/utils/mp-server/send_server_command
+++ b/utils/mp-server/send_server_command
@@ -7,7 +7,10 @@ fi
 SERVER=$1
 SERVERBASE=$HOME/servers/$SERVER
 SOCKET=$SERVERBASE/build/var/run/socket
-
+if ! [ -d "$SERVERBASE" ]; then
+	echo "Server '$SERVER' not found."
+	exit 1
+fi
 if ! [ -e $SOCKET ]; then
 	echo "$SOCKET not found, using the 'oldbuild'."
 	SOCKET=$SERVERBASE/oldbuild/var/run/socket
diff --git a/utils/mp-server/send_server_message b/utils/mp-server/send_server_message
--- a/utils/mp-server/send_server_message
+++ b/utils/mp-server/send_server_message
@@ -7,7 +7,10 @@ fi
 SERVER=$1
 SERVERBASE=$HOME/servers/$SERVER
 SOCKET=$SERVERBASE/build/var/run/socket
-
+if ! [ -d "$SERVERBASE" ]; then
+	echo "Server '$SERVER' not found."
+	exit 1
+fi
 shift
 if [ "$*" == "" ]; then
 	message="The server will get restarted now. Please don't forget to save your game!"
