typo fix

diff --git a/utils/mp-server/send_server_message b/utils/mp-server/send_server_message
--- a/utils/mp-server/send_server_message
+++ b/utils/mp-server/send_server_message
@@ -8,7 +8,7 @@ SERVER=$1
 SERVERBASE=$HOME/servers/$SERVER
 SOCKET=$SERVERBASE/build/var/run/socket
 
-[ -d "$SERVERBASE" ] die "Server '$SERVER' not found."
+[ -d "$SERVERBASE" ] || die "Server '$SERVER' not found."
 shift
 if [ "$*" = "" ]; then
 	message="The server will get restarted now. Please don't forget to save your game!"
