Enable building wesnothd and campaignd

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -279,12 +279,14 @@ jobs:
           ./projectfiles/Xcode/Fix_Xcode_Dependencies
       - name: Build translations
         run: scons translations build=release --debug=time nls=true jobs=2
-      - name: Build wesnoth and unit tests
+      - name: Build wesnoth, wesnothd, campaignd and unit tests
         working-directory: projectfiles/Xcode
         run: |
-          xcodebuild ARCHS=x86_64 -project "The Battle for Wesnoth.xcodeproj" -target "The Battle for Wesnoth" -target "unit_tests" -configuration "$CFG"
+          xcodebuild ARCHS=x86_64 -project "The Battle for Wesnoth.xcodeproj" -configuration "$CFG" -target "The Battle for Wesnoth" -target "unit_tests" -target wesnothd -target campaignd
           # xcodebuild or maybe clang do not appear to fail properly when input files cannot be found; double check executables were produced
           [ -x "build/$CFG/The Battle for Wesnoth.app" ] || { printf 'Failed to build wesnoth executable!\n' >&2; exit 1; }
+          [ -x "build/$CFG/wesnothd"   ] || { printf 'Failed to build wesnothd executable!\n' >&2; exit 1; }
+          [ -x "build/$CFG/campaignd"  ] || { printf 'Failed to build campaignd executable!\n' >&2; exit 1; }
           [ -x "build/$CFG/unit_tests" ] || { printf 'Failed to build unit test executable!\n' >&2; exit 1; }
       - name: Create disk image
         working-directory: projectfiles/Xcode
